---
title: "First Knit"
author: "Diego Martinez Sandoval"
output: 
  html_document:
    number_sections: true
    toc: true
    toc_depth: 5
date: "`r Sys.Date()`"   
---

# A Little Survey

Here are just a few questions so I can get to know you and so you can get practice submitting an assignment in Canvas.  For each question, insert your answer underneath. Make sure each answer is at the minimum a complete sentence with correctly spelled words and correct puncuation. 

## A short history of you.  
Where did you attend High School, and did you graduate? Compare english class to math, is one easier for you than the other? Finally which subject did you do the best in? Your answer should have at least two sentences devoted to each question.  
  
### my answer     
I'm currently enrolled in Pete Knight High School in Palmdale. As a freshmen, 
I'm new to AVC but I'll try my hardest to stay on top of things. I haven't graduated yet because I am currently a 9th grader. I look forward to the day that I can graduate. Math is easier for me to comprehend compared to English. I haven't had too much experience with higher level math yet, but I look forward to learning statistics with you & later on moving onto to more complex forms of math. Currently, as a freshmen, my best grade is in my foreign language (Italian). Second to that, being math. I enjoy both subjects at school. I look forward to continuing my A streak in all classes.  

     


## Your computer and your and its capability?  
 For this class  you need a computer you can use at home.  So, what kind is it (windows, Apple, Linux)?  On a scale of 1 to 10, where 1 is a total dummy (doesn't know a mouse from a keyboard) and 10 is a complete geek (knows computer stuff in and out) How do you rate yourself?  You also need to have have internet access. How is your connection to the internet where you live?

### my answer   
  I have an HP laptop. It's come in handy for a while now & I don't expect it to let me down quite yet. I'll give myself a solid 4 out of 10. I've had experience before with flash drives & importing which gives me a bit more confidence going into this class. I'll give myself the benefit of a doubt & say that compared to others, I can somewhat have my way around electronics. I give myself a 4 because I know I have much more to learn. In the past, due to online learning from the pandemic, I know I have pretty good internet. My internet has always allowed me to be on a zoom call without interruption and do several projects at once. I'm grateful for that. 
   

## Others and You?   
What name do you prefer to be called by your classmates and instructor, if your buddys call you something but you want people in the class to call you something else - what would that be? 

### my answer     
  
I prefer to be called by my name, Diego. My family calls me by my middle name but I prefer that to stick with family. In class, Diego is good. 
 




## Aspirations?   
What do you want to achieve in life?  What college subject do you think would be of the greatest interest to you? What degree or certificate are you trying to achieve?

### my answer     
  
 I can be very ambitious. My goal is to earn a bachelors in architecture and than my doctorate on architecture as well. On top of that, an undergraduate minor degree in Foreign language (Spanish & Italian). I find my interest being in mathematics & foreign language. Being fluent in multiple languages can come in handy when looking for a job in my preferred field. I want to achieve financial freedom through my education. 




## Past adventures?  
Have you ever gone to foreign countries, if so which ones, if not Where might you go in the future?  Have you ever been in the military, if so which branch, if not which branch would you choose if you got drafted, and why?

### my answer     
  
I haven't been able to travel outside the country unfortunately. I have though, traveled a ton inside of the United States. I've traveled all over California (San Francisco, Disneyland, Universal Studios, Yosemite Park, Monterey Bay etc.), to Portland(Oregon), Las Vegas(Nevada), Great Canyon (Arizona), San Antonio (Texas), and various other states. My dream vacation would be to go to Italy. I have the whole trip planned out in my head & I'm learning the language for the fun of it in school. I've never been to the military as I'm 15 but if I were to go, I'd be a marine. I don't get sea sick & I'm good under extremely cold weather. 




## Why are you taking Statistics?  
Did you take Math 115 or Math 116 ?  Did you know Math 115 only satisfies a general education requirement but that Math 116 counts as taking statistics in several transfer institutions??  
What grade do you need to attain in stats to not upset your future plans, What is your plan?  
 

### my answer     
  
  I am taking Math 115. Yes I am aware of that but unfortunately, my schedule didn't align in order to take Math 116. Since I have to take regular high school for the rest of the school year & having summer school during the afternoon in July. Currently, as a 9th grader (upcoming 10th grader) I have straight A's with a 4.6 GPA. I can't expect myself to earn anything lower than an A. My goal is to not let anxiety & pressure get the best of me. This is my first college class, as I am 15. So, it's been quite stressful just thikning about it. But, I will try my hardest to earn the grade I want. 






  




